enum EventRegistry {
    DELETE_NOTE = 'BOARD:WALL:NOTE:DELETE',
    CREATE_NOTE = 'BOARD:WALL:NOTE:CREATE',
    UPDATE_NOTE = 'BOARD:WALL:NOTE:UPDATE',
    UPVOTE = 'BOARD:WALL:NOTE:UPVOTE',

    SORT_BY_VOTES = 'BOARD:WALL:NOTE:SORT:VOTE:DESC',

    CREATE_RETRO_BOARD = 'BOARD:CREATE',
    DELETE_BOARD = 'BOARD:DELETE',
    ERROR = "ERROR",
    CHANGE_BLUR_ON = 'BOARD:BLUR:ON',
    CHANGE_BLUR_OFF = 'BOARD:BLUR:OFF',

}

export default EventRegistry;
